services:
  - type: web
    name: ali-baba-api
    runtime: node
    region: ohio
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - fromGroup: ali-baba-secrets
      - key: PORT
        value: 5000
